using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SPMigrationTool
{
    class CreateListMappings
    {
        DataTable dt = new DataTable();
        public CreateListMappings() {
            createDataTable();
        }

        public DataTable getListMappings() {
            return this.dt;
        }

        public void createDataTable() {
            this.dt.Clear();
            this.dt.Columns.Add("List Name");
            this.dt.Columns.Add("List Type");
            this.dt.Columns.Add("Mapping To List");

            this.dt.Rows.Add(new object[] { "Design Specifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Engineering", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Management", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Quality", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Requirements", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Site Assets", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Shared Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Hardware Design", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Class Development", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ClassLog", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Client Comments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FormClasses", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "FormDesignDocuments", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Instance Development", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "InstanceLog", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Status Log for Dashboard", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "TQLog", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCPCommercialLog", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCPToZCR", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCRLog", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Client Review Design Document", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Review QA/Validation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Design Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "QA / Validation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Information", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Design Specs Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Hardware Design Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Quality Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Change Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "FAT Software Fault Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Decision Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Document Library", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Genzyme Inputs", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Reference", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Lilly Design Specifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Scratch", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "01 Commercial", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "02 Project Management", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "03 Quality", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "03 Software Design", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "04 Hardware Design", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "06 Procurement", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "07 Test Protocols & Reports", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "08 Configurations", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "09 Correspondence", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Files", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Comms", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZCR Log", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Documents for Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Hardware", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Front End Study", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Procurement", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZCP", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZCR", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Review Design Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "DocStatus", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "NintexFormXml", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Redlines", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZT Comments Response", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "DocStatus", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "DocStatus2", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "1.0 CMM", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.1 Comms", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.2 QSV", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.3 Project Inputs", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.4 Engineering", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.5 Meeting", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.6 Project Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.7 PM", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.8 Procurement", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.9 FEED Deliverables", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Comments Library", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Delivery Software Fault Forms", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "SCR", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "System Acceptance Fault Forms", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Code Review Forms", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Comms Library", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Delivery Software Fault Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Proposal", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "SCRLog", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "System Acceptance Fault Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Health Check Tools", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Quarterly Reports", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Concast 1", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Concast 2", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Concast 3", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Meeting Minutes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "QUARTERLY REVIEWS", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "SITE BACKUPS", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Managment", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.0_CMM", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.1_Comms", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.2_QSV", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.3_Project Inputs", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.4_Engineering", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.5_Meetings", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.6_Project Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.7_PM", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.8_Procurement", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "1.9_Pfizer Workspace", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "As Built Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Approval Folder", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Review Folder", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Code Review Forms - OLD DO NOT USE", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Zenith Change Requests", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Study Information", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Hardware Approval Folder", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Hardware Review Folder", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Software Approval Folder", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Software Review Folder", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Common Project Files", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Code Reviews", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Communications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Zenith Change Control", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Controls", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Class Develpment", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Client Docs for Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Comms Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Engineering Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZCR Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Comments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Comments - OLD - DO NOT USE", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Design Documents - OLD DO NOT USE", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Engineering - OLD DO NOT USE", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Quality - OLD - DO NOT USE", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Document Control", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FAT Software Incident Management Log", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Planova Contacts List", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "TQ Forms", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "DDL", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Class", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "EM Code Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TQ", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "+/- 10% Estimate", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ProjectInfoExt", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCR Attachments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Class Develpment", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Bio Requirement", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Workshops", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Code Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FAT Hardware Fault Form", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "FAT Software Fault Form", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "FAT Software Observation Forms", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "NintexFormExportXml", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Test", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Test Client", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Test Client Comments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TQ", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "TQ Client", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCR", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "IML", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Test Specifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Design Specifications OLD - DO NOT USE", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "DesignSpecs", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Zenith Change Log", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Design Specs (Client Review)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Hardware Design (Client Review)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Quality (Client Review)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Design Specifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Quality & Test Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Administration", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Administration (DO NOT USE)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Design Specifications (DO NOT USE)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Engineering (DO NOT USE)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Hardware Design (DO NOT USE)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Management (DO NOT USE)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Notes (DO NOT USE)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Quality (DO NOT USE)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Requirements (DO NOT USE)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Test Library", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "03 Requirements", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "04 Design Specifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "05 Hardware Design", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "06 Quality", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "07 Procurement", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "08 Test Protocols & Specifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "09 Configurations", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "10 Correspondence", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project SOP's", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Commercial", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "IO Access", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Validation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Drawings", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Functional Specification", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Operator Manual", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Software Design Specification", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Software Module Design Specifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Hardware Supply 15-08", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Quality and Validation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PUS Master Files", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Sponsor Meetings", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Shared Docs", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "DesignSpecifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ProjectNotes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "AbbVie Reporting", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Doc Reviews", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Admin", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Inputs and Collaboration", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Decision Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Functional Specifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Kickoff Meeting", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Plans and Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "SFAT Documentation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZCR Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Client Comment Review Tracker", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Code Review Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Code Shakedown Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Design Review Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "GE Document Comment Tracker", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Internal Test Fix Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "MES Code Review Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Quality Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Shakedown Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Test Documentation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Test Execution", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "test List", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Unwitnessed FAT Fault Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Unwitnessed FAT Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Unwitnessed FAT Observation Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "RECIPES", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Code Review Documentation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Engineering Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Guidelines", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Management", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Shakedown Documentation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ALM Client Collaboration", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ALM Delivery Package", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ALM Engineering Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ALM Quality", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ALM SFAT & DSAT Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ALM Specifications Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ALM Specifications WIP", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ALM Testing", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Baseline Documents & Database", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "CC1 Client Collaboration", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "CC1 Engineering Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "CC1 Quality", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "CC1 SFAT & DSAT Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "CC1 Specifications Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "CC1 Specifications WIP", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "CC1 Testing", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Approved Documentation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Baseline Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "CodeReviewLog", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Delivery Packages", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Object Tracking Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "OOS Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "PIT Client Collaboration", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PIT Delivery Package", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PIT Engineering Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PIT Quality", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PIT SFAT & DSAT Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PIT Specifications Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PIT Specifications WIP", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PIT Testing", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Problem Statements", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Project Management Client", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Management ZT", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Plans", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Shakedown Log", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TQ / Decision Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Transmittal Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Validation Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Engineering Notes and Tools", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Functional Specs Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Functionals Specifications", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Input and Collaboration Client", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Input and Collaboration Subc", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Project Plans Client", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "SFAT Documentation Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Site Testing Documentation Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Testing", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TQ Decision Log Client", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCR Log Client2", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "TQ Attachments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TQ Client Review", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Client Inputs & Collaboration", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Engineering Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Internal Test Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Objects", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Project Contacts", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Project Plans & Notes", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Documents DO NOT USE", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Technical Queries Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Deliverables", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Deployments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Instructions", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Meetings", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Training", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZCRToZCR", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Assessment Report", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZCR Client Review", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Logs", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZCRNew", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Doc Control", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Shire", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Zenith Internal", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "01. VCAT XPS Output", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "02. Module Difference Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "03. Modules Under Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "04. 10-Jan-18 Difference Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "05. Grangecastle Documents 17-Jan-18", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "06. Implementation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Code", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCR Review", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCRAttachments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Approved Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Document Generation Templates", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "MES Design", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PAS Design", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PI Design", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "SFS's for Info", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Signed ZCRs", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Templates", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TQ Client Attachments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TQ Zenith Attachments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TQAttachments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "ZCRCR2", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCRCR3", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZTDesignDocViews", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "AccountSettingList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "AdobeSignTokenList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "AgreementList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "DataMappingList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "MergeMappingList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "OauthSessionList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "PersonalSettingList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "RememberSelectionList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Client Review QA / Validation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Consultancy Report", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Design Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client QA / Validation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FRS Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TQ Decision Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Change Controls ZCR&ZCP", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client External Directory", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Design Specification", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "RTM", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "User Manual", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Documentation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Document Comment Tracker", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Incident Log", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCP", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCP Client Review", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCPAttachments", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Design Specs", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "error logs", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Test MS", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client As Built Documents", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FAT Test Hardware Fault Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FAT Test Hardware Observation Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FAT Test Software Fault Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FAT Test Software Observation Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Internal Test Hardware Fault Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Internal Test Hardware Observation Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Internal Test Software Fault Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Internal Test Software Observation Form", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "CM Code Review Forms", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Risk Register", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Document Upload Center", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "GE - Pfizer Documentation Standard", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "GSK Bio - Belgium - Adjusco Project", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "GSK DeltaV v's PSC7 TCO", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Guidelines and Operating Philosphy", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Janssen - Gurabo - Project  InSPiRe2", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Janssen Latina", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "JnJ DeltaV v's PCS7 TCO", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Pfizer - Grangecastle - Drug Substance TCS Evaluation", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "PHE - Porton Down - 3000L Fermenation Suite Study", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "File Repository", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Nicks List", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Cork Chem", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Emerson - RFI - Queries", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "General Information", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Gurabo (Parenterals)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Internal Janssen Folder", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Leiden", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Request for Proposal", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Schaffhausen", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Schneider - RFI - Queries", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Office 365 Licenses", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "test", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Test Agresso Info", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Test Project List", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Testing Agresso List", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Dashboards", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Protocols", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Adobe Sign - ZT", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Client Approved Documents (generated)", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Document Printout Templates", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Docusign - ZT", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Observation Form", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "PAS Design Client Review", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "TestDocList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "TestFormList", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Content Organizer Rules", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Drop Off Library", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "NFAY_Doc_Workflow", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "NFAY_Test_Lib_External", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "NFAYTESTLIB", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "Nintex Software Fault Form", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "AliciaTest", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FAT Observation Forms Test", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "FAT Software Fault Form Test", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "FAT Software Fault Form Test2", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Flow Test", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "NFAY_ProposalSetUp", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Org Chart Test", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "PMO Workflow", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Power Apps", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ProjectInformation", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Sales", "DocumentLibrary", "Shared Documents" });
            this.dt.Rows.Add(new object[] { "sitename", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Test Users List", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "WebMergeLogs", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "ZCP - Ken", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "Places", "GenericList", "TestList" });
            this.dt.Rows.Add(new object[] { "TestList", "GenericList", "TestList" });

        }
    }
}
